-- ==========================================
-- Full Schema Migration for Link Generator
-- Run this in Supabase SQL Editor
-- ==========================================

-- 1. Create domains table
CREATE TABLE public.domains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create team table
CREATE TABLE public.team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    user_id TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create links table
CREATE TABLE public.links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    original_url TEXT NOT NULL,
    title TEXT,
    description TEXT,
    image_url TEXT,
    domain_id BIGINT REFERENCES public.domains(id),
    user_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create clicks table
CREATE TABLE public.clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id BIGINT REFERENCES public.links(id),
    slug TEXT,
    country TEXT,
    city TEXT,
    ip_address TEXT,
    user_agent TEXT,
    referer TEXT,
    os TEXT,
    device TEXT,
    browser TEXT,
    click_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create settings table
CREATE TABLE public.settings (
    key TEXT PRIMARY KEY,
    value TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Create indexes
CREATE INDEX idx_clicks_link_id ON public.clicks(link_id);
CREATE INDEX idx_clicks_slug ON public.clicks(slug);
CREATE INDEX idx_clicks_created_at ON public.clicks(created_at);
CREATE INDEX idx_links_user_id ON public.links(user_id);
CREATE INDEX idx_links_slug ON public.links(slug);

-- 7. Create trigger function for settings updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 8. Create trigger for settings table
CREATE TRIGGER update_settings_updated_at
    BEFORE UPDATE ON public.settings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 9. Enable RLS and create policies for ALL tables

-- Domains
ALTER TABLE domains ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON domains FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON domains FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON domains FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON domains FOR DELETE USING (true);

-- Team
ALTER TABLE team ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON team FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON team FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON team FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON team FOR DELETE USING (true);

-- Links
ALTER TABLE links ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON links FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON links FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON links FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON links FOR DELETE USING (true);

-- Clicks
ALTER TABLE clicks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON clicks FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON clicks FOR INSERT WITH CHECK (true);

-- Settings
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON settings FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON settings FOR UPDATE USING (true);

-- 10. Insert default domains
INSERT INTO public.domains (url) VALUES 
('l.404family.com'),
('link.example.com'),
('go.example.com'),
('s.example.com');
